# Generated by Django 3.2.9 on 2021-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=100)),
                ('kitchen_address', models.CharField(max_length=100)),
                ('kitchen_desc', models.CharField(max_length=500)),
                ('cuisine_type', models.CharField(max_length=100)),
            ],
        ),
    ]
