# Generated by Django 3.2.9 on 2021-11-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_desc',
            field=models.TextField(),
        ),
    ]
