# Generated by Django 3.2.9 on 2021-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_alter_kitchen_kitchen_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
