# Generated by Django 3.2.9 on 2021-11-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
